### PR TITLE
Migrate to null safety

### PR DESCRIPTION
**Pull request by lucas-gauer**

### CODE REVIEW

**Comment by MichaelDark** [comment]
@danilocoppi Could you release 2.0 version to `pub.dev`, please?

**Comment by csciallano** [comment]
@danilocoppi Hi, yes that would be great thank you !

**Comment by dinahapuque** [comment]
@danilocoppi any prevision to release this?

**Comment by itsJoKr** [comment]
Bump. Can you publish this to pub? Shouldn't take much time.

**Pull request merged**
